### ISSUE TITLE
Use of "Investigation"

### ISSUE THREAD

**Issue by mhep** [jasonwinning/hypernomicon#1]
I was hoping you could give a quick overview of how the "investigation" category is meant to work in Hypernomicon? 

I am really enjoying this genius program so far!

**Comment by jasonwinning** [comment]
Sure, Investigation records are a way of providing a description of a person's ongoing research project, which can include a number of works they've authored. You add an Investigation record on the Persons tab by clicking "Add new investigation". For example, in my Person record for Daniel Dennett, there are 3 Investigation records: "Agency and Free Will", "Intentional Stance", and "Consciousness". You can assign an investigation to a work in the Persons tab, by clicking in the Investigation column on the list of works, or on the Works tab in the Investigations sub-tab. When an Investigation tab is selected on the Persons tab, only works attached to that Investigation are displayed in the list of works. As with many other types of records, you can assign a search key to an Investigation on its tab. Overall, it is a way of grouping a given author's works and prevents you from writing a large amount of text on the Person's main description field.

**Comment by mhep** [comment]
Very interesting, thanks! 

My first intuition was to use the Investigation records as my own investigation into an author's work along certain themes. Then again, that may not be that different from ordering a person's work.

Thanks so much for your quick response!
